import {
  Beige,
  BlackChrome,
  Black,
  Brown,
  GoldChrome,
  Green,
  Mahogany,
  Oak,
  Red,
  StandardChrome,
  White,
  BROWN_NS_BW,
  BLACK_TR_BK_50P,
  BROWN_NS_BW_87_M_PM,
  GREEN_DL_GR_31,
  GREEN_DL_GR_84_PE,
  GREEN_DL_GR,
  GREEN_DL,
  GREY_LC_BW_62_M_PM,
  GREY_LC_BW,
  RED_DL_RD_34_PE,
  RED_DL_RD,
  SILVER_AT_BG_50_M_PE,
  SILVER_AT_BG,
  SILVER_DL_RD_30_M_PE,
  SILVER_DL_YE_45_M_PEG,
  WHITE_NS_WH_15_PE,
  WHITE_NS_WH,
  SILVER_DL_YE,
  SILVER_LC_RD,
  YELLOW_DL_YE_78_PE,
  YELLOW_DL_YE,
} from '../assets/colors/colors';

export const SWATCH_COLOR_CODES = {
  'WHITE NS WH 86/PE': White,
  'BLACK DL BK 49/M/PE': Black,
  'BROWN DL BW 30/M/PE': Brown,
  'GREEN DL GR 42/PG': Green,
  'RED DL RD 45': Red,
  'BEIGE DL BG 25/PG': Beige,
  'Black chrome plating': BlackChrome,
  'Gold chrome plating': GoldChrome,
  'Standard chrome plating': StandardChrome,
  Oak: Oak,
  Mahogany: Mahogany,
  'BROWN NS BW': BROWN_NS_BW,

  // Maestosa Body
  'BLACK TR BK 50/P': BLACK_TR_BK_50P,
  'BROWN NS BW 87/M/PM': BROWN_NS_BW_87_M_PM,
  'GREEN DL GR 31': GREEN_DL_GR_31,
  'GREEN DL GR 84/PE': GREEN_DL_GR_84_PE,
  'RED DL RD 34/PE': RED_DL_RD_34_PE,
  'YELLOW DL YE 78/PE': YELLOW_DL_YE_78_PE,
  'SILVER AT BG 50/M/PE': SILVER_AT_BG_50_M_PE,
  'GREY LC BW 62/M/PM': GREY_LC_BW_62_M_PM,
  'SILVER DL RD 30/M/PE': SILVER_DL_RD_30_M_PE,
  'SILVER DL YE 45/M/PEG': SILVER_DL_YE_45_M_PEG,
  'WHITE NS WH 15/PE': WHITE_NS_WH_15_PE,

  // Maestosa Dot Pattern
  'WHITE NS WH': WHITE_NS_WH,
  'YELLOW DL YE': YELLOW_DL_YE,
  'RED DL RD': RED_DL_RD,
  'GREEN DL GR': GREEN_DL_GR,
  'GREEN DL': GREEN_DL,
  'SILVER DL YE': SILVER_DL_YE,
  'SILVER LC RD': SILVER_LC_RD,
  'BROWN NS BW': BROWN_NS_BW,
  'SILVER AT BG': SILVER_AT_BG,
  'GREY LC BW': GREY_LC_BW,
};

export const SWATCH_COLOR_NAMES = {
  'WHITE NS WH 86/PE': 'White',
  'BLACK DL BK 49/M/PE': 'Black',
  'BROWN DL BW 30/M/PE': 'Brown',
  'GREEN DL GR 42/PG': 'Green',
  'RED DL RD 45': 'Red',
  'BEIGE DL BG 25/PG': 'Beige',
  'Black chrome plating': 'Black chrome plating',
  'Gold chrome plating': 'Gold chrome plating',
  'Standard chrome plating': 'Standard chrome plating',
  Oak: 'Oak',
  Mahogany: 'Mahogany',
  Off: 'None',

  // Maestosa Body
  'BLACK TR BK 50/P': 'Black',
  'BROWN NS BW 87/M/PM': 'Brown',
  'GREEN DL GR 31': 'GREEN_DL_GR_31',
  'GREEN DL GR 84/PE': 'GREEN_DL_GR_84_PE',
  'RED DL RD 34/PE': 'Red',
  'YELLOW DL YE 78/PE': 'Yellow',
  'SILVER AT BG 50/M/PE': 'SILVER_AT_BG_50_M_PE',
  'GREY LC BW 62/M/PM': 'Grey',
  'SILVER DL RD 30/M/PE': 'SILVER_DL_RD_30_M_PE',
  'SILVER DL YE 45/M/PEG': 'SILVER_DL_YE_45_M_PEG',
  'WHITE NS WH 15/PE': 'White',
  // Maestosa Dot Pattern
  'WHITE NS WH': 'White',
  'YELLOW DL YE': 'Yellow',
  'RED DL RD': 'Red',
  'GREEN DL GR': 'GREEN_DL_GR',
  'GREEN DL': 'GREEN_DL',
  'SILVER DL YE': 'SILVER_DL_YE',
  'SILVER LC RD': 'SILVER_LC_RD',
  'BROWN NS BW': 'Brown',
  'SILVER AT BG': 'SILVER_AT_BG',
  'GREY LC BW': 'Grey',
};

export const SWATCH_IMAGE_NAMES = {
  // 'WHITE NS WH': WHITE_NS_WH,
  // 'YELLOW DL YE': YELLOW_DL_YE,
  // 'RED DL RD': RED_DL_RD,
  // 'GREEN DL GR': GREEN_DL_GR,
  // 'GREEN DL': GREEN_DL,
  // 'SILVER DL YE': SILVER_DL_YE,
  // 'SILVER LC RD': SILVER_LC_RD,
  // 'BROWN NS BW': BROWN_NS_BW,
  // 'SILVER AT BG': SILVER_AT_BG,
  // 'GREY LC BW': GREY_LC_BW,
};
